--- 
- 
  become: true
  hosts: webservers
  tasks: 
    - 
      ignore_erros: true
      name: "Cleaning Environment"
      shell: "sudo rm /var/www/html/index.html"
    - 
      name: "Check if apache is installed"
      package_facts: 
        manager: auto
    - 
      debug: 
        msg: "apache found"
      name: "apache test result"
      when: "'httpd' in ansible_facts.packages"
    - 
      debug: 
        msg: "apache not found"
      name: "apache test result"
      when: "'httpd' not in ansible_facts.packages"
    - 
      name: "Install apache packages"
      when: "'httpd' not in ansible_facts.packages"
      yum: 
        name: httpd
        state: present
    - 
      name: "Start Apache server"
      service: 
        enabled: true
        name: httpd
        state: started
    - 
      copy: 
        dest: /var/www/html/
        src: index.html
      name: "Deploy static website"
