---
- hosts: webservers 
  become: True
  tasks:
    - name: Cleaning Environment
      shell: sudo rm /var/www/html/index.html
      ignore_erros: true
      
    
    - name: Check if apache is installed
      package_facts:
        manager: auto

    - name: apache test result
      debug:
        msg: "apache found"
      when: "'httpd' in ansible_facts.packages"

    - name: apache test result
      debug:
        msg: "apache not found"
      when: "'httpd' not in ansible_facts.packages"
      
    - name: Install apache packages
      yum:
        name: "httpd"
        state: "present"
      when: "'httpd' not in ansible_facts.packages"
      
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
        
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
